backend:
    name: git-gateway # Prod
    repo: recrea-t/arquengin
    branch: main

local_backend: true

media_folder: static/images
public_folder: /images

site_url: https://arquengin.netlify.app
display_url: https://arquengin.netlify.app
logo_url: https://arquengin.netlify.app/images/Logo.jpg

show_preview_links: false

locale: "ca"

collections:
    - name: 'pages' # Used in routes, e.g., /admin/collections/blog
      label: 'Pàgines' # Used in the UI
      description: 'Modifica els camps importants per a cadascuna de les pàgines del lloc web.'
      extension: 'md'
      format: frontmatter
      create: false
      delete: false
      editor:
        preview: false
      files:
        - name: 'home'
          label: Inici
          file: 'src/pages/index.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatge
              name: hero
              widget: image
              allow_multiple: false
            - label: Arquitectura
              name: arquitectura
              widget: list
              summary: "{{fields.item}}"
              field: {widget: string, name: item, label: Item}
              minimize_collapsed: true
              label_singular: "servei d'arquitectura"
            - label: Enginyeria
              name: enginyeria
              widget: list
              summary: "{{fields.item}}"
              field: {widget: string, name: item, label: Item}
              minimize_collapsed: true
              label_singular: "servei d'enginyeria"
            - label: Interiorisme
              name: interiorisme
              widget: list
              summary: "{{fields.item}}"
              field: {widget: string, name: item, label: Item}
              minimize_collapsed: true
              label_singular: "servei d'interiorisme"
        - name: 'about'
          label: 'Qui som'
          file: 'src/pages/qui-som.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Imatge
              name: image
              widget: image
              allow_multiple: false
            - label: Persones
              name: people
              widget: list
              allow_add: false
              fields:
                - label: Nom
                  name: title
                  widget: string
                - label: Resum
                  name: summary
                  widget: markdown
                - label: Descripció
                  name: description
                  widget: markdown
                  required: false
        - name: 'services'
          label: 'Serveis'
          file: 'src/pages/serveis.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - name: services
              label: Serveis
              widget: list
              allow_add: false
              summary: "{{fields.title}}"
              fields:
                - name: id
                  label: Id
                  widget: hidden
                - name: className
                  label: Classe
                  widget: hidden
                - label: Títol
                  name: title
                  widget: string
                - label: Descripció
                  name: description
                  widget: markdown
                - label: Serveis
                  name: list
                  widget: list
                  summary: "{{fields.item}}"
                  field: {widget: string, name: item, label: Item}
                  minimize_collapsed: true
                  label_singular: "servei"
                - label: Seccions
                  name: sections
                  required: false
                  widget: list
                  label_singular: "secció"
                  fields:
                    - label: Nom
                      name: title
                      widget: string
                    - label: Descripció
                      name: description
                      widget: markdown
                    - label: Llistat
                      name: list
                      widget: list
                      minimize_collapsed: true
                      label_singular: "element"
                      fields:
                        - label: Nom
                          name: title
                          widget: string
                        - label: Enllaços
                          name: links
                          widget: list
                          required: false
                          minimize_collapsed: true
                          label_singular: "enllaç"
                          fields:
                            - label: Títol
                              name: title
                              widget: string
                            - label: URL
                              name: url
                              widget: string
        - name: 'projects'
          label: 'Projectes'
          file: 'src/pages/projectes.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Text
              name: text
              widget: markdown
            - name: projectes
              label: Projectes
              widget: list
              minimize_collapsed: true
              add_to_top: true
              summary: "{{fields.title}}"
              fields:
                - label: Nom
                  name: title
                  widget: string
                - label: Categoria
                  name: category
                  widget: select
                  options: ["habitatge", "rehabilitació", "espai comercial"]
                - label: Descripció
                  name: description
                  widget: markdown
                - label: Imatges
                  name: images
                  widget: list
                  minimize_collapsed: true
                  label_singular: imatge
                  fields:
                    - label: Text alternatiu
                      name: alt
                      widget: string
                    - label: Imatge
                      name: src
                      widget: image
                      media_folder: "../../static/images/projectes/"
                      allow_multiple: false
        - name: 'contact'
          label: 'Contacte'
          file: 'src/pages/contacte.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Text
              name: text
              widget: markdown
        - name: 'legal-notice'
          label: 'Avís legal'
          file: 'src/pages/avis-legal.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Cos
              name: body
              widget: markdown
        - name: 'privacy-policy'
          label: 'Protecció de dades'
          file: 'src/pages/politica-de-proteccio-de-dades.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Cos
              name: body
              widget: markdown
        - name: '404'
          label: '404'
          file: 'src/pages/404.md'
          fields:
            - label: Títol (SEO)
              name: title
              widget: string
            - label: Descripció (SEO)
              name: description
              widget: text
            - label: Cos
              name: body
              widget: markdown
