---
label: services
hide_body: true
fields:
- type: text
  name: templateKey
  label: templateKey
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: field_group_list
  name: services
  label: services
  fields:
  - type: text
    name: id
    label: id
  - type: text
    name: title
    label: title
  - type: text
    name: className
    label: className
  - type: textarea
    name: description
    label: description
  - type: list
    name: list
    label: list
  - type: text
    name: sections
    label: sections
